apiVersion: skaffold/v1beta10
kind: Config

profiles:

- name: build-image

  build:
    artifacts:
    - image: aisuko/skaffold-example
      kaniko:
        # flags: ["--cache=true"]
        image: aisuko/kaniko-project-executor:latest
        buildContext:
          localDir: {}
            # initImage: Dockerfile
        cache: {}
    # tagPolicy:
    #   envTemplate:
    #     template: "{{.IMAGE_NAME}}:{{.FOO}}"
    # local:
    #   push: true
    #   useDockerCLI: false
    #   useBuildkit: false

    cluster:
      pullSecretName: aisuko-regis
      namespace: default
      # dockerConfig:
      #   path: ~/.docker/config.json
      # resources:
      #   requests:
      #     cpu: 200m
      #     memory: 100Mi
      #   limits:
      #     cpu: 200m
      #     memory: 100Mi

# - name: test-image

#   test:
#   - image: aisuko/skaffold-example:v1
#     structureTests:
#     - ./test/*

# - name: deploy-image
  
#   deploy:
#     kubectl:
#       manifests:
#       - k8s-*

build:
  artifacts:
  - image: aisuko/skaffold-example
    kaniko:
      # flags: ["--cache=true"]
      image: aisuko/kaniko-project-executor:latest
      buildContext:
        localDir: {}
            # initImage: Dockerfile
      cache: {}
    # tagPolicy:
    #   envTemplate:
    #     template: "{{.IMAGE_NAME}}:{{.FOO}}"
    # local:
    #   push: true
    #   useDockerCLI: false
    #   useBuildkit: false

  cluster:
    pullSecretName: aisuko-regis
    namespace: default
  