apiVersion: skaffold/v1beta10
kind: Config
build:
  tagPolicy:
    envTemplate:
      # export FOO=v1
      template: "{{.IMAGE_NAME}}:{{.FOO}}"
  artifacts:
  - image: aisuko/skaffold
  local: {}

deploy:
  kubectl:
    manifests:
      - k8s-*