apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:
  inputs:
    resources:
      - name: docker-source
        type: git
    params:
      - name: pathToDockerFile
        description: The path to the dockerfile to build
        default: /workspace/docker-source/Dockerfile
      - name: pathToContext
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace/docker-source
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: aisuko/kaniko-project-executor:latest
      
      env:
      - name: DOCKER_CONFIG
        value: /builder/home/.docker
      
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.pathToDockerFile}
        - --destination=${outputs.resources.builtImage.url}
        - --context=${inputs.params.pathToContext}
      
      # The PR was solved the issue, but I believe there would be a better solution
      # https://github.com/tektoncd/catalog/pull/22

      # volumenmounts:
      #   - name: docker-config
      #     mountPath: /kaniko/.docker/
      # volumes:
      #   - name: docker-config
      #     configMap:
      #       name: docker-config